nelmio_api_doc:
    documentation:
        info:
            title: Kubo API
            description: API de recettes.
            version: 1.0.0
        servers:
            - url: /
              description: Serveur courant
    areas:
        default:
            path_patterns:
                - ^/api(?!/doc$)
