<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260424122335 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE refresh_tokens (refresh_token VARCHAR(128) NOT NULL, username VARCHAR(255) NOT NULL, valid TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_9BACE7E1C74F2195 ON refresh_tokens (refresh_token)');
        $this->addSql('CREATE TABLE users (id UUID NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1483A5E9E7927C74 ON users (email)');
        $this->addSql('ALTER TABLE ingredients ALTER mois_saison TYPE JSON');
        $this->addSql('ALTER INDEX idx_ing_type RENAME TO IDX_4B60114FC54C8C93');
        $this->addSql('ALTER INDEX uniq_type_ing_nom RENAME TO UNIQ_79C6DE6C6E55B5');
        $this->addSql('ALTER INDEX uniq_type_ing_slug RENAME TO UNIQ_79C6DE989D9B62');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE refresh_tokens');
        $this->addSql('DROP TABLE users');
        $this->addSql('ALTER TABLE ingredients ALTER mois_saison TYPE JSONB');
        $this->addSql('ALTER INDEX idx_4b60114fc54c8c93 RENAME TO idx_ing_type');
        $this->addSql('ALTER INDEX uniq_79c6de989d9b62 RENAME TO uniq_type_ing_slug');
        $this->addSql('ALTER INDEX uniq_79c6de6c6e55b5 RENAME TO uniq_type_ing_nom');
    }
}
