<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260317112828 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE allergenes (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(150) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_CBFDFAD66C6E55B5 ON allergenes (nom)');
        $this->addSql('CREATE TABLE etapes (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, numero INT NOT NULL, instructions JSON NOT NULL, astuce TEXT DEFAULT NULL, recette_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_E3443E1789312FE9 ON etapes (recette_id)');
        $this->addSql('CREATE TABLE ingredients (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_4B60114F6C6E55B5 ON ingredients (nom)');
        $this->addSql('CREATE TABLE nutrition_faits (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, contexte VARCHAR(10) NOT NULL, energie_kj DOUBLE PRECISION DEFAULT NULL, energie_kcal DOUBLE PRECISION DEFAULT NULL, matieres_grasses DOUBLE PRECISION DEFAULT NULL, acides_gras_satures DOUBLE PRECISION DEFAULT NULL, glucides DOUBLE PRECISION DEFAULT NULL, sucres DOUBLE PRECISION DEFAULT NULL, fibres DOUBLE PRECISION DEFAULT NULL, proteines DOUBLE PRECISION DEFAULT NULL, sel DOUBLE PRECISION DEFAULT NULL, potassium DOUBLE PRECISION DEFAULT NULL, calcium DOUBLE PRECISION DEFAULT NULL, cholesterol DOUBLE PRECISION DEFAULT NULL, fer DOUBLE PRECISION DEFAULT NULL, acides_gras_trans DOUBLE PRECISION DEFAULT NULL, recette_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_FFBE715D89312FE9 ON nutrition_faits (recette_id)');
        $this->addSql('CREATE UNIQUE INDEX uq_nutrition_recette_contexte ON nutrition_faits (recette_id, contexte)');
        $this->addSql('CREATE TABLE recette_ingredients (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, quantite VARCHAR(50) DEFAULT NULL, unite VARCHAR(50) DEFAULT NULL, raw VARCHAR(512) NOT NULL, recette_id INT NOT NULL, ingredient_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B413140689312FE9 ON recette_ingredients (recette_id)');
        $this->addSql('CREATE INDEX IDX_B4131406933FE08C ON recette_ingredients (ingredient_id)');
        $this->addSql('CREATE TABLE recettes (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, slug VARCHAR(255) NOT NULL, url VARCHAR(512) NOT NULL, nom VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, difficulte VARCHAR(20) DEFAULT NULL, temps_total INT DEFAULT NULL, temps_preparation INT DEFAULT NULL, nb_personnes INT NOT NULL, image_url VARCHAR(512) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_EB48E72C989D9B62 ON recettes (slug)');
        $this->addSql('CREATE TABLE recette_tags (recette_id INT NOT NULL, tag_id INT NOT NULL, PRIMARY KEY (recette_id, tag_id))');
        $this->addSql('CREATE INDEX IDX_22BC7E7D89312FE9 ON recette_tags (recette_id)');
        $this->addSql('CREATE INDEX IDX_22BC7E7DBAD26311 ON recette_tags (tag_id)');
        $this->addSql('CREATE TABLE recette_allergenes (recette_id INT NOT NULL, allergene_id INT NOT NULL, PRIMARY KEY (recette_id, allergene_id))');
        $this->addSql('CREATE INDEX IDX_B792C30F89312FE9 ON recette_allergenes (recette_id)');
        $this->addSql('CREATE INDEX IDX_B792C30F4646AB2 ON recette_allergenes (allergene_id)');
        $this->addSql('CREATE TABLE recette_ustensiles (recette_id INT NOT NULL, ustensile_id INT NOT NULL, PRIMARY KEY (recette_id, ustensile_id))');
        $this->addSql('CREATE INDEX IDX_EDD6DDD789312FE9 ON recette_ustensiles (recette_id)');
        $this->addSql('CREATE INDEX IDX_EDD6DDD7B78A4282 ON recette_ustensiles (ustensile_id)');
        $this->addSql('CREATE TABLE tags (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(100) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_6FBC94266C6E55B5 ON tags (nom)');
        $this->addSql('CREATE TABLE ustensiles (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(150) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_91B9E40E6C6E55B5 ON ustensiles (nom)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0 ON messenger_messages (queue_name)');
        $this->addSql('CREATE INDEX IDX_75EA56E0E3BD61CE ON messenger_messages (available_at)');
        $this->addSql('CREATE INDEX IDX_75EA56E016BA31DB ON messenger_messages (delivered_at)');
        $this->addSql('ALTER TABLE etapes ADD CONSTRAINT FK_E3443E1789312FE9 FOREIGN KEY (recette_id) REFERENCES recettes (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE nutrition_faits ADD CONSTRAINT FK_FFBE715D89312FE9 FOREIGN KEY (recette_id) REFERENCES recettes (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE recette_ingredients ADD CONSTRAINT FK_B413140689312FE9 FOREIGN KEY (recette_id) REFERENCES recettes (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE recette_ingredients ADD CONSTRAINT FK_B4131406933FE08C FOREIGN KEY (ingredient_id) REFERENCES ingredients (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE recette_tags ADD CONSTRAINT FK_22BC7E7D89312FE9 FOREIGN KEY (recette_id) REFERENCES recettes (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE recette_tags ADD CONSTRAINT FK_22BC7E7DBAD26311 FOREIGN KEY (tag_id) REFERENCES tags (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE recette_allergenes ADD CONSTRAINT FK_B792C30F89312FE9 FOREIGN KEY (recette_id) REFERENCES recettes (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE recette_allergenes ADD CONSTRAINT FK_B792C30F4646AB2 FOREIGN KEY (allergene_id) REFERENCES allergenes (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE recette_ustensiles ADD CONSTRAINT FK_EDD6DDD789312FE9 FOREIGN KEY (recette_id) REFERENCES recettes (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE recette_ustensiles ADD CONSTRAINT FK_EDD6DDD7B78A4282 FOREIGN KEY (ustensile_id) REFERENCES ustensiles (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE etapes DROP CONSTRAINT FK_E3443E1789312FE9');
        $this->addSql('ALTER TABLE nutrition_faits DROP CONSTRAINT FK_FFBE715D89312FE9');
        $this->addSql('ALTER TABLE recette_ingredients DROP CONSTRAINT FK_B413140689312FE9');
        $this->addSql('ALTER TABLE recette_ingredients DROP CONSTRAINT FK_B4131406933FE08C');
        $this->addSql('ALTER TABLE recette_tags DROP CONSTRAINT FK_22BC7E7D89312FE9');
        $this->addSql('ALTER TABLE recette_tags DROP CONSTRAINT FK_22BC7E7DBAD26311');
        $this->addSql('ALTER TABLE recette_allergenes DROP CONSTRAINT FK_B792C30F89312FE9');
        $this->addSql('ALTER TABLE recette_allergenes DROP CONSTRAINT FK_B792C30F4646AB2');
        $this->addSql('ALTER TABLE recette_ustensiles DROP CONSTRAINT FK_EDD6DDD789312FE9');
        $this->addSql('ALTER TABLE recette_ustensiles DROP CONSTRAINT FK_EDD6DDD7B78A4282');
        $this->addSql('DROP TABLE allergenes');
        $this->addSql('DROP TABLE etapes');
        $this->addSql('DROP TABLE ingredients');
        $this->addSql('DROP TABLE nutrition_faits');
        $this->addSql('DROP TABLE recette_ingredients');
        $this->addSql('DROP TABLE recettes');
        $this->addSql('DROP TABLE recette_tags');
        $this->addSql('DROP TABLE recette_allergenes');
        $this->addSql('DROP TABLE recette_ustensiles');
        $this->addSql('DROP TABLE tags');
        $this->addSql('DROP TABLE ustensiles');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
